[2025-01-19T03:52:48.664+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-19T03:52:48.673+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generate_portfolio.run_fargate_task manual__2025-01-19T03:52:47.904600+00:00 [queued]>
[2025-01-19T03:52:48.678+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generate_portfolio.run_fargate_task manual__2025-01-19T03:52:47.904600+00:00 [queued]>
[2025-01-19T03:52:48.678+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-19T03:52:48.684+0000] {taskinstance.py:2889} INFO - Executing <Task(EcsRunTaskOperator): run_fargate_task> on 2025-01-19 03:52:47.904600+00:00
[2025-01-19T03:52:48.686+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2447) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-19T03:52:48.687+0000] {standard_task_runner.py:72} INFO - Started process 2448 to run task
[2025-01-19T03:52:48.688+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'generate_portfolio', 'run_fargate_task', 'manual__2025-01-19T03:52:47.904600+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/portfolio.py', '--cfg-path', '/tmp/tmpqp23e134']
[2025-01-19T03:52:48.689+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask run_fargate_task
[2025-01-19T03:52:48.722+0000] {task_command.py:467} INFO - Running <TaskInstance: generate_portfolio.run_fargate_task manual__2025-01-19T03:52:47.904600+00:00 [running]> on host 5c920dd7060b
[2025-01-19T03:52:48.764+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Pedro' AIRFLOW_CTX_DAG_ID='generate_portfolio' AIRFLOW_CTX_TASK_ID='run_fargate_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-19T03:52:47.904600+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-19T03:52:47.904600+00:00'
[2025-01-19T03:52:48.764+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-19T03:52:48.766+0000] {ecs.py:506} INFO - Running ECS Task - Task definition: qam-tasks - on cluster AirflowECSCluster
[2025-01-19T03:52:48.766+0000] {ecs.py:509} INFO - EcsOperator overrides: {'containerOverrides': [{'name': 'test-task', 'command': ['test.py']}]}
[2025-01-19T03:52:48.771+0000] {base.py:84} INFO - Retrieving connection 'aws_ecr'
[2025-01-19T03:52:48.772+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='aws_ecr', conn_type='aws') credentials retrieved from login and password.
[2025-01-19T03:52:49.014+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 520, in execute
    self._start_task()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 620, in _start_task
    response = self.client.run_task(**run_opts)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the RunTask operation: User: arn:aws:iam::059575417638:user/***-ecs is not authorized to perform: iam:PassRole on resource: arn:aws:iam::059575417638:role/ecsTaskExecutionRole because no identity-based policy allows the iam:PassRole action
[2025-01-19T03:52:49.020+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=generate_portfolio, task_id=run_fargate_task, run_id=manual__2025-01-19T03:52:47.904600+00:00, execution_date=20250119T035247, start_date=20250119T035248, end_date=20250119T035249
[2025-01-19T03:52:49.027+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-19T03:52:49.028+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task run_fargate_task (An error occurred (AccessDeniedException) when calling the RunTask operation: User: arn:aws:iam::059575417638:user/***-ecs is not authorized to perform: iam:PassRole on resource: arn:aws:iam::059575417638:role/ecsTaskExecutionRole because no identity-based policy allows the iam:PassRole action; 2448)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 520, in execute
    self._start_task()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 620, in _start_task
    response = self.client.run_task(**run_opts)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the RunTask operation: User: arn:aws:iam::059575417638:user/***-ecs is not authorized to perform: iam:PassRole on resource: arn:aws:iam::059575417638:role/ecsTaskExecutionRole because no identity-based policy allows the iam:PassRole action
[2025-01-19T03:52:49.041+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-19T03:52:49.050+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-19T03:52:49.051+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
